export const obj = [{
    question: "Which of the following is a client site language?",
    a: "Java",
    b: "C",
    c: "Python",
    d: "JavaScript",
    correct: "d",
},{
    question: "Javascript is an _______ language?",
    a: "Object-Oriented",
    b: "Object-Based",
    c: "Python",
    d: "Procedural",
    correct: "a",
},{
    question: "Which of the following keywords is used to define a variable in Javascript?",
    a: "var",
    b: "let",
    c: "Both A and B",
    d: "None of the Above",
    correct: "c",
},{
    question: "What is JavaScript?",
    a: "JavaScript is a scripting language used to make the website interactive",
    b: "JavaScript is an assembly language used to make the website interactive",
    c: "JavaScript is a compiled language used to make the website interactive",
    d: "None of the mentioned",
    correct: "a",
},{
    question: "Arrays in JavaScript are defined by which of the following statements?",
    a: "It is an ordered list of values",
    b: "It is an ordered list of objects",
    c: "It is an ordered list of string",
    d: "It is an ordered list of functions",
    correct: "a",
},{
    question: "Which of the following is not javascript data types?",
    a: "Null type",
    b: "Undefined type",
    c: "Number type",
    d: "All of the mentioned",
    correct: "d",
},{
    question: "Which of the following can be used to call a JavaScript Code Snippet?",
    a: "Function/Method",
    b: "Preprocessor",
    c: "Triggering Event",
    d: "RMI",
    correct: "a",
},{
    question: "Why JavaScript Engine is needed?",
    a: "Both Compiling & Interpreting the JavaScript",
    b: "Parsing the javascript",
    c: "Interpreting the JavaScript",
    d: "Compiling the JavaScript",
    correct: "c",
},{
    question: "Which of the following is the property that is triggered in response to JS errors?",
    a: "onclick",
    b: "onerror",
    c: "onmessage",
    d: "onexception",
    correct: "b",
},{
    question: "Which of the following is not an error in JavaScript?",
    a: "Missing of Bracket",
    b: "Division by zero",
    c: "Syntax error",
    d: "Missing of semicolons",
    correct: "b",
},

]